// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protocol_v3.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol
{

    /// <summary>Holder for reflection information generated from Protocol_v3.proto</summary>
    public static partial class ProtocolV3Reflection
    {

        #region Descriptor
        /// <summary>File descriptor for Protocol_v3.proto</summary>
        public static pbr::FileDescriptor Descriptor
        {
            get { return descriptor; }
        }
        private static pbr::FileDescriptor descriptor;

        static ProtocolV3Reflection()
        {
            byte[] descriptorData = global::System.Convert.FromBase64String(
                string.Concat(
                  "ChFQcm90b2NvbF92My5wcm90bxIIUHJvdG9jb2wiKgoEVXNlchIQCghVc2Vy",
                  "bmFtZRgBIAEoCRIQCghQYXNzd29yZBgCIAEoCSI3CgtQYXJ0aWNpcGFudBIK",
                  "CgJJRBgBIAEoBRIMCgROYW1lGAIgASgJEg4KBlBvaW50cxgDIAEoBSIjCgRS",
                  "YWNlEgoKAklEGAEgASgFEg8KB1JlZmVyZWUYAiABKAkiTgoNUGFydGljaXBh",
                  "dGlvbhIKCgJJRBgBIAEoBRITCgtQYXJ0aWNpcGFudBgCIAEoBRIMCgRSYWNl",
                  "GAMgASgFEg4KBlBvaW50cxgEIAEoBSLyAgoHUmVxdWVzdBIkCgR0eXBlGAEg",
                  "ASgOMhYuUHJvdG9jb2wuUmVxdWVzdC5UeXBlEh4KBHVzZXIYAiABKAsyDi5Q",
                  "cm90b2NvbC5Vc2VySAASLAoLcGFydGljaXBhbnQYAyABKAsyFS5Qcm90b2Nv",
                  "bC5QYXJ0aWNpcGFudEgAEh4KBHJhY2UYBCABKAsyDi5Qcm90b2NvbC5SYWNl",
                  "SAASMAoNcGFydGljaXBhdGlvbhgFIAEoCzIXLlByb3RvY29sLlBhcnRpY2lw",
                  "YXRpb25IACKVAQoEVHlwZRIJCgVMT0dJThAAEgoKBkxPR09VVBABEg4KClVQ",
                  "REFURV9BTEwQAhIHCgNBREQQAxIKCgZSRU1PVkUQBBIKCgZVUERBVEUQBRII",
                  "CgRGSU5EEAYSFAoQR0VUX1BBUlRJQ0lQQU5UUxAHEg0KCUdFVF9SQUNFUxAI",
                  "EhYKEkdFVF9QQVJUSUNJUEFUSU9OUxAJQgkKB3BheWxvYWQiswMKCFJlc3Bv",
                  "bnNlEiUKBHR5cGUYASABKA4yFy5Qcm90b2NvbC5SZXNwb25zZS5UeXBlEg0K",
                  "BWVycm9yGAIgASgJEioKC3BhcnRpY2lwYW50GAMgASgLMhUuUHJvdG9jb2wu",
                  "UGFydGljaXBhbnQSHAoEcmFjZRgEIAEoCzIOLlByb3RvY29sLlJhY2USLgoN",
                  "cGFydGljaXBhdGlvbhgFIAEoCzIXLlByb3RvY29sLlBhcnRpY2lwYXRpb24S",
                  "KwoMcGFydGljaXBhbnRzGAYgAygLMhUuUHJvdG9jb2wuUGFydGljaXBhbnQS",
                  "HQoFcmFjZXMYByADKAsyDi5Qcm90b2NvbC5SYWNlEi8KDnBhcnRpY2lwYXRp",
                  "b25zGAggAygLMhcuUHJvdG9jb2wuUGFydGljaXBhdGlvbiJ6CgRUeXBlEgYK",
                  "Ak9LEAASCAoERkFJTBABEgkKBUVSUk9SEAISDgoKVVBEQVRFX0FMTBADEggK",
                  "BEZJTkQQBBIUChBHRVRfUEFSVElDSVBBTlRTEAUSDQoJR0VUX1JBQ0VTEAYS",
                  "FgoSR0VUX1BBUlRJQ0lQQVRJT05TEAdCHQoQTmV0d29yay5Qcm90b2NvbEIJ",
                  "UHJvdG9idWZzYgZwcm90bzM="));
            descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
                new pbr::FileDescriptor[] { },
                new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.User), global::Protocol.User.Parser, new[]{ "Username", "Password" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.Participant), global::Protocol.Participant.Parser, new[]{ "ID", "Name", "Points" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.Race), global::Protocol.Race.Parser, new[]{ "ID", "Referee" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.Participation), global::Protocol.Participation.Parser, new[]{ "ID", "Participant", "Race", "Points" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.Request), global::Protocol.Request.Parser, new[]{ "Type", "User", "Participant", "Race", "Participation" }, new[]{ "Payload" }, new[]{ typeof(global::Protocol.Request.Types.Type) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.Response), global::Protocol.Response.Parser, new[]{ "Type", "Error", "Participant", "Race", "Participation", "Participants", "Races", "Participations" }, null, new[]{ typeof(global::Protocol.Response.Types.Type) }, null, null)
                }));
        }
        #endregion

    }
    #region Messages
    [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
    public sealed partial class User : pb::IMessage<User>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<User> _parser = new pb::MessageParser<User>(() => new User());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<User> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Protocol.ProtocolV3Reflection.Descriptor.MessageTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public User()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public User(User other) : this()
        {
            username_ = other.username_;
            password_ = other.password_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public User Clone()
        {
            return new User(this);
        }

        /// <summary>Field number for the "Username" field.</summary>
        public const int UsernameFieldNumber = 1;
        private string username_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Username
        {
            get { return username_; }
            set
            {
                username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "Password" field.</summary>
        public const int PasswordFieldNumber = 2;
        private string password_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Password
        {
            get { return password_; }
            set
            {
                password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as User);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(User other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (Username != other.Username) return false;
            if (Password != other.Password) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (Username.Length != 0) hash ^= Username.GetHashCode();
            if (Password.Length != 0) hash ^= Password.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (Username.Length != 0)
            {
                output.WriteRawTag(10);
                output.WriteString(Username);
            }
            if (Password.Length != 0)
            {
                output.WriteRawTag(18);
                output.WriteString(Password);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (Username.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
            }
            if (Password.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(User other)
        {
            if (other == null)
            {
                return;
            }
            if (other.Username.Length != 0)
            {
                Username = other.Username;
            }
            if (other.Password.Length != 0)
            {
                Password = other.Password;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 10:
                        {
                            Username = input.ReadString();
                            break;
                        }
                    case 18:
                        {
                            Password = input.ReadString();
                            break;
                        }
                }
            }
        }
#endif

    }

    [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
    public sealed partial class Participant : pb::IMessage<Participant>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<Participant> _parser = new pb::MessageParser<Participant>(() => new Participant());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Participant> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Protocol.ProtocolV3Reflection.Descriptor.MessageTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Participant()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Participant(Participant other) : this()
        {
            iD_ = other.iD_;
            name_ = other.name_;
            points_ = other.points_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Participant Clone()
        {
            return new Participant(this);
        }

        /// <summary>Field number for the "ID" field.</summary>
        public const int IDFieldNumber = 1;
        private int iD_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int ID
        {
            get { return iD_; }
            set
            {
                iD_ = value;
            }
        }

        /// <summary>Field number for the "Name" field.</summary>
        public const int NameFieldNumber = 2;
        private string name_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Name
        {
            get { return name_; }
            set
            {
                name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "Points" field.</summary>
        public const int PointsFieldNumber = 3;
        private int points_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int Points
        {
            get { return points_; }
            set
            {
                points_ = value;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as Participant);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Participant other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (ID != other.ID) return false;
            if (Name != other.Name) return false;
            if (Points != other.Points) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (ID != 0) hash ^= ID.GetHashCode();
            if (Name.Length != 0) hash ^= Name.GetHashCode();
            if (Points != 0) hash ^= Points.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (ID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ID);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Points != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Points);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (ID != 0)
            {
                output.WriteRawTag(8);
                output.WriteInt32(ID);
            }
            if (Name.Length != 0)
            {
                output.WriteRawTag(18);
                output.WriteString(Name);
            }
            if (Points != 0)
            {
                output.WriteRawTag(24);
                output.WriteInt32(Points);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (ID != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeInt32Size(ID);
            }
            if (Name.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
            }
            if (Points != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeInt32Size(Points);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Participant other)
        {
            if (other == null)
            {
                return;
            }
            if (other.ID != 0)
            {
                ID = other.ID;
            }
            if (other.Name.Length != 0)
            {
                Name = other.Name;
            }
            if (other.Points != 0)
            {
                Points = other.Points;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ID = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            Points = input.ReadInt32();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 8:
                        {
                            ID = input.ReadInt32();
                            break;
                        }
                    case 18:
                        {
                            Name = input.ReadString();
                            break;
                        }
                    case 24:
                        {
                            Points = input.ReadInt32();
                            break;
                        }
                }
            }
        }
#endif

    }

    [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
    public sealed partial class Race : pb::IMessage<Race>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<Race> _parser = new pb::MessageParser<Race>(() => new Race());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Race> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Protocol.ProtocolV3Reflection.Descriptor.MessageTypes[2]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Race()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Race(Race other) : this()
        {
            iD_ = other.iD_;
            referee_ = other.referee_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Race Clone()
        {
            return new Race(this);
        }

        /// <summary>Field number for the "ID" field.</summary>
        public const int IDFieldNumber = 1;
        private int iD_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int ID
        {
            get { return iD_; }
            set
            {
                iD_ = value;
            }
        }

        /// <summary>Field number for the "Referee" field.</summary>
        public const int RefereeFieldNumber = 2;
        private string referee_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Referee
        {
            get { return referee_; }
            set
            {
                referee_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as Race);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Race other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (ID != other.ID) return false;
            if (Referee != other.Referee) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (ID != 0) hash ^= ID.GetHashCode();
            if (Referee.Length != 0) hash ^= Referee.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (ID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ID);
      }
      if (Referee.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Referee);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (ID != 0)
            {
                output.WriteRawTag(8);
                output.WriteInt32(ID);
            }
            if (Referee.Length != 0)
            {
                output.WriteRawTag(18);
                output.WriteString(Referee);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (ID != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeInt32Size(ID);
            }
            if (Referee.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Referee);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Race other)
        {
            if (other == null)
            {
                return;
            }
            if (other.ID != 0)
            {
                ID = other.ID;
            }
            if (other.Referee.Length != 0)
            {
                Referee = other.Referee;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ID = input.ReadInt32();
            break;
          }
          case 18: {
            Referee = input.ReadString();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 8:
                        {
                            ID = input.ReadInt32();
                            break;
                        }
                    case 18:
                        {
                            Referee = input.ReadString();
                            break;
                        }
                }
            }
        }
#endif

    }

    [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
    public sealed partial class Participation : pb::IMessage<Participation>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<Participation> _parser = new pb::MessageParser<Participation>(() => new Participation());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Participation> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Protocol.ProtocolV3Reflection.Descriptor.MessageTypes[3]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Participation()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Participation(Participation other) : this()
        {
            iD_ = other.iD_;
            participant_ = other.participant_;
            race_ = other.race_;
            points_ = other.points_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Participation Clone()
        {
            return new Participation(this);
        }

        /// <summary>Field number for the "ID" field.</summary>
        public const int IDFieldNumber = 1;
        private int iD_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int ID
        {
            get { return iD_; }
            set
            {
                iD_ = value;
            }
        }

        /// <summary>Field number for the "Participant" field.</summary>
        public const int ParticipantFieldNumber = 2;
        private int participant_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int Participant
        {
            get { return participant_; }
            set
            {
                participant_ = value;
            }
        }

        /// <summary>Field number for the "Race" field.</summary>
        public const int RaceFieldNumber = 3;
        private int race_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int Race
        {
            get { return race_; }
            set
            {
                race_ = value;
            }
        }

        /// <summary>Field number for the "Points" field.</summary>
        public const int PointsFieldNumber = 4;
        private int points_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int Points
        {
            get { return points_; }
            set
            {
                points_ = value;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as Participation);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Participation other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (ID != other.ID) return false;
            if (Participant != other.Participant) return false;
            if (Race != other.Race) return false;
            if (Points != other.Points) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (ID != 0) hash ^= ID.GetHashCode();
            if (Participant != 0) hash ^= Participant.GetHashCode();
            if (Race != 0) hash ^= Race.GetHashCode();
            if (Points != 0) hash ^= Points.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (ID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ID);
      }
      if (Participant != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Participant);
      }
      if (Race != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Race);
      }
      if (Points != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Points);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (ID != 0)
            {
                output.WriteRawTag(8);
                output.WriteInt32(ID);
            }
            if (Participant != 0)
            {
                output.WriteRawTag(16);
                output.WriteInt32(Participant);
            }
            if (Race != 0)
            {
                output.WriteRawTag(24);
                output.WriteInt32(Race);
            }
            if (Points != 0)
            {
                output.WriteRawTag(32);
                output.WriteInt32(Points);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (ID != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeInt32Size(ID);
            }
            if (Participant != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeInt32Size(Participant);
            }
            if (Race != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeInt32Size(Race);
            }
            if (Points != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeInt32Size(Points);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Participation other)
        {
            if (other == null)
            {
                return;
            }
            if (other.ID != 0)
            {
                ID = other.ID;
            }
            if (other.Participant != 0)
            {
                Participant = other.Participant;
            }
            if (other.Race != 0)
            {
                Race = other.Race;
            }
            if (other.Points != 0)
            {
                Points = other.Points;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ID = input.ReadInt32();
            break;
          }
          case 16: {
            Participant = input.ReadInt32();
            break;
          }
          case 24: {
            Race = input.ReadInt32();
            break;
          }
          case 32: {
            Points = input.ReadInt32();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 8:
                        {
                            ID = input.ReadInt32();
                            break;
                        }
                    case 16:
                        {
                            Participant = input.ReadInt32();
                            break;
                        }
                    case 24:
                        {
                            Race = input.ReadInt32();
                            break;
                        }
                    case 32:
                        {
                            Points = input.ReadInt32();
                            break;
                        }
                }
            }
        }
#endif

    }

    [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
    public sealed partial class Request : pb::IMessage<Request>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Request> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Protocol.ProtocolV3Reflection.Descriptor.MessageTypes[4]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Request()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Request(Request other) : this()
        {
            type_ = other.type_;
            switch (other.PayloadCase)
            {
                case PayloadOneofCase.User:
                    User = other.User.Clone();
                    break;
                case PayloadOneofCase.Participant:
                    Participant = other.Participant.Clone();
                    break;
                case PayloadOneofCase.Race:
                    Race = other.Race.Clone();
                    break;
                case PayloadOneofCase.Participation:
                    Participation = other.Participation.Clone();
                    break;
            }

            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Request Clone()
        {
            return new Request(this);
        }

        /// <summary>Field number for the "type" field.</summary>
        public const int TypeFieldNumber = 1;
        private global::Protocol.Request.Types.Type type_ = global::Protocol.Request.Types.Type.Login;
        /// <summary>
        /// Identifies which request is filled in.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Protocol.Request.Types.Type Type
        {
            get { return type_; }
            set
            {
                type_ = value;
            }
        }

        /// <summary>Field number for the "user" field.</summary>
        public const int UserFieldNumber = 2;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Protocol.User User
        {
            get { return payloadCase_ == PayloadOneofCase.User ? (global::Protocol.User)payload_ : null; }
            set
            {
                payload_ = value;
                payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.User;
            }
        }

        /// <summary>Field number for the "participant" field.</summary>
        public const int ParticipantFieldNumber = 3;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Protocol.Participant Participant
        {
            get { return payloadCase_ == PayloadOneofCase.Participant ? (global::Protocol.Participant)payload_ : null; }
            set
            {
                payload_ = value;
                payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Participant;
            }
        }

        /// <summary>Field number for the "race" field.</summary>
        public const int RaceFieldNumber = 4;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Protocol.Race Race
        {
            get { return payloadCase_ == PayloadOneofCase.Race ? (global::Protocol.Race)payload_ : null; }
            set
            {
                payload_ = value;
                payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Race;
            }
        }

        /// <summary>Field number for the "participation" field.</summary>
        public const int ParticipationFieldNumber = 5;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Protocol.Participation Participation
        {
            get { return payloadCase_ == PayloadOneofCase.Participation ? (global::Protocol.Participation)payload_ : null; }
            set
            {
                payload_ = value;
                payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Participation;
            }
        }

        private object payload_;
        /// <summary>Enum of possible cases for the "payload" oneof.</summary>
        public enum PayloadOneofCase
        {
            None = 0,
            User = 2,
            Participant = 3,
            Race = 4,
            Participation = 5,
        }
        private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public PayloadOneofCase PayloadCase
        {
            get { return payloadCase_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearPayload()
        {
            payloadCase_ = PayloadOneofCase.None;
            payload_ = null;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as Request);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Request other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (Type != other.Type) return false;
            if (!object.Equals(User, other.User)) return false;
            if (!object.Equals(Participant, other.Participant)) return false;
            if (!object.Equals(Race, other.Race)) return false;
            if (!object.Equals(Participation, other.Participation)) return false;
            if (PayloadCase != other.PayloadCase) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (Type != global::Protocol.Request.Types.Type.Login) hash ^= Type.GetHashCode();
            if (payloadCase_ == PayloadOneofCase.User) hash ^= User.GetHashCode();
            if (payloadCase_ == PayloadOneofCase.Participant) hash ^= Participant.GetHashCode();
            if (payloadCase_ == PayloadOneofCase.Race) hash ^= Race.GetHashCode();
            if (payloadCase_ == PayloadOneofCase.Participation) hash ^= Participation.GetHashCode();
            hash ^= (int)payloadCase_;
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (Type != global::Protocol.Request.Types.Type.Login) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.User) {
        output.WriteRawTag(18);
        output.WriteMessage(User);
      }
      if (payloadCase_ == PayloadOneofCase.Participant) {
        output.WriteRawTag(26);
        output.WriteMessage(Participant);
      }
      if (payloadCase_ == PayloadOneofCase.Race) {
        output.WriteRawTag(34);
        output.WriteMessage(Race);
      }
      if (payloadCase_ == PayloadOneofCase.Participation) {
        output.WriteRawTag(42);
        output.WriteMessage(Participation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (Type != global::Protocol.Request.Types.Type.Login)
            {
                output.WriteRawTag(8);
                output.WriteEnum((int)Type);
            }
            if (payloadCase_ == PayloadOneofCase.User)
            {
                output.WriteRawTag(18);
                output.WriteMessage(User);
            }
            if (payloadCase_ == PayloadOneofCase.Participant)
            {
                output.WriteRawTag(26);
                output.WriteMessage(Participant);
            }
            if (payloadCase_ == PayloadOneofCase.Race)
            {
                output.WriteRawTag(34);
                output.WriteMessage(Race);
            }
            if (payloadCase_ == PayloadOneofCase.Participation)
            {
                output.WriteRawTag(42);
                output.WriteMessage(Participation);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (Type != global::Protocol.Request.Types.Type.Login)
            {
                size += 1 + pb::CodedOutputStream.ComputeEnumSize((int)Type);
            }
            if (payloadCase_ == PayloadOneofCase.User)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(User);
            }
            if (payloadCase_ == PayloadOneofCase.Participant)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(Participant);
            }
            if (payloadCase_ == PayloadOneofCase.Race)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(Race);
            }
            if (payloadCase_ == PayloadOneofCase.Participation)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(Participation);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Request other)
        {
            if (other == null)
            {
                return;
            }
            if (other.Type != global::Protocol.Request.Types.Type.Login)
            {
                Type = other.Type;
            }
            switch (other.PayloadCase)
            {
                case PayloadOneofCase.User:
                    if (User == null)
                    {
                        User = new global::Protocol.User();
                    }
                    User.MergeFrom(other.User);
                    break;
                case PayloadOneofCase.Participant:
                    if (Participant == null)
                    {
                        Participant = new global::Protocol.Participant();
                    }
                    Participant.MergeFrom(other.Participant);
                    break;
                case PayloadOneofCase.Race:
                    if (Race == null)
                    {
                        Race = new global::Protocol.Race();
                    }
                    Race.MergeFrom(other.Race);
                    break;
                case PayloadOneofCase.Participation:
                    if (Participation == null)
                    {
                        Participation = new global::Protocol.Participation();
                    }
                    Participation.MergeFrom(other.Participation);
                    break;
            }

            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Protocol.Request.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            global::Protocol.User subBuilder = new global::Protocol.User();
            if (payloadCase_ == PayloadOneofCase.User) {
              subBuilder.MergeFrom(User);
            }
            input.ReadMessage(subBuilder);
            User = subBuilder;
            break;
          }
          case 26: {
            global::Protocol.Participant subBuilder = new global::Protocol.Participant();
            if (payloadCase_ == PayloadOneofCase.Participant) {
              subBuilder.MergeFrom(Participant);
            }
            input.ReadMessage(subBuilder);
            Participant = subBuilder;
            break;
          }
          case 34: {
            global::Protocol.Race subBuilder = new global::Protocol.Race();
            if (payloadCase_ == PayloadOneofCase.Race) {
              subBuilder.MergeFrom(Race);
            }
            input.ReadMessage(subBuilder);
            Race = subBuilder;
            break;
          }
          case 42: {
            global::Protocol.Participation subBuilder = new global::Protocol.Participation();
            if (payloadCase_ == PayloadOneofCase.Participation) {
              subBuilder.MergeFrom(Participation);
            }
            input.ReadMessage(subBuilder);
            Participation = subBuilder;
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 8:
                        {
                            Type = (global::Protocol.Request.Types.Type)input.ReadEnum();
                            break;
                        }
                    case 18:
                        {
                            global::Protocol.User subBuilder = new global::Protocol.User();
                            if (payloadCase_ == PayloadOneofCase.User)
                            {
                                subBuilder.MergeFrom(User);
                            }
                            input.ReadMessage(subBuilder);
                            User = subBuilder;
                            break;
                        }
                    case 26:
                        {
                            global::Protocol.Participant subBuilder = new global::Protocol.Participant();
                            if (payloadCase_ == PayloadOneofCase.Participant)
                            {
                                subBuilder.MergeFrom(Participant);
                            }
                            input.ReadMessage(subBuilder);
                            Participant = subBuilder;
                            break;
                        }
                    case 34:
                        {
                            global::Protocol.Race subBuilder = new global::Protocol.Race();
                            if (payloadCase_ == PayloadOneofCase.Race)
                            {
                                subBuilder.MergeFrom(Race);
                            }
                            input.ReadMessage(subBuilder);
                            Race = subBuilder;
                            break;
                        }
                    case 42:
                        {
                            global::Protocol.Participation subBuilder = new global::Protocol.Participation();
                            if (payloadCase_ == PayloadOneofCase.Participation)
                            {
                                subBuilder.MergeFrom(Participation);
                            }
                            input.ReadMessage(subBuilder);
                            Participation = subBuilder;
                            break;
                        }
                }
            }
        }
#endif

        #region Nested types
        /// <summary>Container for nested types declared in the Request message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types
        {
            public enum Type
            {
                [pbr::OriginalName("LOGIN")] Login = 0,
                [pbr::OriginalName("LOGOUT")] Logout = 1,
                [pbr::OriginalName("UPDATE_ALL")] UpdateAll = 2,
                [pbr::OriginalName("ADD")] Add = 3,
                [pbr::OriginalName("REMOVE")] Remove = 4,
                [pbr::OriginalName("UPDATE")] Update = 5,
                [pbr::OriginalName("FIND")] Find = 6,
                [pbr::OriginalName("GET_PARTICIPANTS")] GetParticipants = 7,
                [pbr::OriginalName("GET_RACES")] GetRaces = 8,
                [pbr::OriginalName("GET_PARTICIPATIONS")] GetParticipations = 9,
            }

        }
        #endregion

    }

    [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
    public sealed partial class Response : pb::IMessage<Response>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Response> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Protocol.ProtocolV3Reflection.Descriptor.MessageTypes[5]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Response()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Response(Response other) : this()
        {
            type_ = other.type_;
            error_ = other.error_;
            participant_ = other.participant_ != null ? other.participant_.Clone() : null;
            race_ = other.race_ != null ? other.race_.Clone() : null;
            participation_ = other.participation_ != null ? other.participation_.Clone() : null;
            participants_ = other.participants_.Clone();
            races_ = other.races_.Clone();
            participations_ = other.participations_.Clone();
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Response Clone()
        {
            return new Response(this);
        }

        /// <summary>Field number for the "type" field.</summary>
        public const int TypeFieldNumber = 1;
        private global::Protocol.Response.Types.Type type_ = global::Protocol.Response.Types.Type.Ok;
        /// <summary>
        /// Identifies which request is filled in.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Protocol.Response.Types.Type Type
        {
            get { return type_; }
            set
            {
                type_ = value;
            }
        }

        /// <summary>Field number for the "error" field.</summary>
        public const int ErrorFieldNumber = 2;
        private string error_ = "";
        /// <summary>
        /// One of the following will be filled in, depending on the type.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Error
        {
            get { return error_; }
            set
            {
                error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "participant" field.</summary>
        public const int ParticipantFieldNumber = 3;
        private global::Protocol.Participant participant_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Protocol.Participant Participant
        {
            get { return participant_; }
            set
            {
                participant_ = value;
            }
        }

        /// <summary>Field number for the "race" field.</summary>
        public const int RaceFieldNumber = 4;
        private global::Protocol.Race race_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Protocol.Race Race
        {
            get { return race_; }
            set
            {
                race_ = value;
            }
        }

        /// <summary>Field number for the "participation" field.</summary>
        public const int ParticipationFieldNumber = 5;
        private global::Protocol.Participation participation_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Protocol.Participation Participation
        {
            get { return participation_; }
            set
            {
                participation_ = value;
            }
        }

        /// <summary>Field number for the "participants" field.</summary>
        public const int ParticipantsFieldNumber = 6;
        private static readonly pb::FieldCodec<global::Protocol.Participant> _repeated_participants_codec
            = pb::FieldCodec.ForMessage(50, global::Protocol.Participant.Parser);
        private readonly pbc::RepeatedField<global::Protocol.Participant> participants_ = new pbc::RepeatedField<global::Protocol.Participant>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<global::Protocol.Participant> Participants
        {
            get { return participants_; }
        }

        /// <summary>Field number for the "races" field.</summary>
        public const int RacesFieldNumber = 7;
        private static readonly pb::FieldCodec<global::Protocol.Race> _repeated_races_codec
            = pb::FieldCodec.ForMessage(58, global::Protocol.Race.Parser);
        private readonly pbc::RepeatedField<global::Protocol.Race> races_ = new pbc::RepeatedField<global::Protocol.Race>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<global::Protocol.Race> Races
        {
            get { return races_; }
        }

        /// <summary>Field number for the "participations" field.</summary>
        public const int ParticipationsFieldNumber = 8;
        private static readonly pb::FieldCodec<global::Protocol.Participation> _repeated_participations_codec
            = pb::FieldCodec.ForMessage(66, global::Protocol.Participation.Parser);
        private readonly pbc::RepeatedField<global::Protocol.Participation> participations_ = new pbc::RepeatedField<global::Protocol.Participation>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<global::Protocol.Participation> Participations
        {
            get { return participations_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as Response);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Response other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (Type != other.Type) return false;
            if (Error != other.Error) return false;
            if (!object.Equals(Participant, other.Participant)) return false;
            if (!object.Equals(Race, other.Race)) return false;
            if (!object.Equals(Participation, other.Participation)) return false;
            if (!participants_.Equals(other.participants_)) return false;
            if (!races_.Equals(other.races_)) return false;
            if (!participations_.Equals(other.participations_)) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (Type != global::Protocol.Response.Types.Type.Ok) hash ^= Type.GetHashCode();
            if (Error.Length != 0) hash ^= Error.GetHashCode();
            if (participant_ != null) hash ^= Participant.GetHashCode();
            if (race_ != null) hash ^= Race.GetHashCode();
            if (participation_ != null) hash ^= Participation.GetHashCode();
            hash ^= participants_.GetHashCode();
            hash ^= races_.GetHashCode();
            hash ^= participations_.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (Type != global::Protocol.Response.Types.Type.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      if (participant_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Participant);
      }
      if (race_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Race);
      }
      if (participation_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Participation);
      }
      participants_.WriteTo(output, _repeated_participants_codec);
      races_.WriteTo(output, _repeated_races_codec);
      participations_.WriteTo(output, _repeated_participations_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (Type != global::Protocol.Response.Types.Type.Ok)
            {
                output.WriteRawTag(8);
                output.WriteEnum((int)Type);
            }
            if (Error.Length != 0)
            {
                output.WriteRawTag(18);
                output.WriteString(Error);
            }
            if (participant_ != null)
            {
                output.WriteRawTag(26);
                output.WriteMessage(Participant);
            }
            if (race_ != null)
            {
                output.WriteRawTag(34);
                output.WriteMessage(Race);
            }
            if (participation_ != null)
            {
                output.WriteRawTag(42);
                output.WriteMessage(Participation);
            }
            participants_.WriteTo(ref output, _repeated_participants_codec);
            races_.WriteTo(ref output, _repeated_races_codec);
            participations_.WriteTo(ref output, _repeated_participations_codec);
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (Type != global::Protocol.Response.Types.Type.Ok)
            {
                size += 1 + pb::CodedOutputStream.ComputeEnumSize((int)Type);
            }
            if (Error.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
            }
            if (participant_ != null)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(Participant);
            }
            if (race_ != null)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(Race);
            }
            if (participation_ != null)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(Participation);
            }
            size += participants_.CalculateSize(_repeated_participants_codec);
            size += races_.CalculateSize(_repeated_races_codec);
            size += participations_.CalculateSize(_repeated_participations_codec);
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Response other)
        {
            if (other == null)
            {
                return;
            }
            if (other.Type != global::Protocol.Response.Types.Type.Ok)
            {
                Type = other.Type;
            }
            if (other.Error.Length != 0)
            {
                Error = other.Error;
            }
            if (other.participant_ != null)
            {
                if (participant_ == null)
                {
                    Participant = new global::Protocol.Participant();
                }
                Participant.MergeFrom(other.Participant);
            }
            if (other.race_ != null)
            {
                if (race_ == null)
                {
                    Race = new global::Protocol.Race();
                }
                Race.MergeFrom(other.Race);
            }
            if (other.participation_ != null)
            {
                if (participation_ == null)
                {
                    Participation = new global::Protocol.Participation();
                }
                Participation.MergeFrom(other.Participation);
            }
            participants_.Add(other.participants_);
            races_.Add(other.races_);
            participations_.Add(other.participations_);
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Protocol.Response.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            if (participant_ == null) {
              Participant = new global::Protocol.Participant();
            }
            input.ReadMessage(Participant);
            break;
          }
          case 34: {
            if (race_ == null) {
              Race = new global::Protocol.Race();
            }
            input.ReadMessage(Race);
            break;
          }
          case 42: {
            if (participation_ == null) {
              Participation = new global::Protocol.Participation();
            }
            input.ReadMessage(Participation);
            break;
          }
          case 50: {
            participants_.AddEntriesFrom(input, _repeated_participants_codec);
            break;
          }
          case 58: {
            races_.AddEntriesFrom(input, _repeated_races_codec);
            break;
          }
          case 66: {
            participations_.AddEntriesFrom(input, _repeated_participations_codec);
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 8:
                        {
                            Type = (global::Protocol.Response.Types.Type)input.ReadEnum();
                            break;
                        }
                    case 18:
                        {
                            Error = input.ReadString();
                            break;
                        }
                    case 26:
                        {
                            if (participant_ == null)
                            {
                                Participant = new global::Protocol.Participant();
                            }
                            input.ReadMessage(Participant);
                            break;
                        }
                    case 34:
                        {
                            if (race_ == null)
                            {
                                Race = new global::Protocol.Race();
                            }
                            input.ReadMessage(Race);
                            break;
                        }
                    case 42:
                        {
                            if (participation_ == null)
                            {
                                Participation = new global::Protocol.Participation();
                            }
                            input.ReadMessage(Participation);
                            break;
                        }
                    case 50:
                        {
                            participants_.AddEntriesFrom(ref input, _repeated_participants_codec);
                            break;
                        }
                    case 58:
                        {
                            races_.AddEntriesFrom(ref input, _repeated_races_codec);
                            break;
                        }
                    case 66:
                        {
                            participations_.AddEntriesFrom(ref input, _repeated_participations_codec);
                            break;
                        }
                }
            }
        }
#endif

        #region Nested types
        /// <summary>Container for nested types declared in the Response message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types
        {
            public enum Type
            {
                [pbr::OriginalName("OK")] Ok = 0,
                [pbr::OriginalName("FAIL")] Fail = 1,
                [pbr::OriginalName("ERROR")] Error = 2,
                [pbr::OriginalName("UPDATE_ALL")] UpdateAll = 3,
                [pbr::OriginalName("FIND")] Find = 4,
                [pbr::OriginalName("GET_PARTICIPANTS")] GetParticipants = 5,
                [pbr::OriginalName("GET_RACES")] GetRaces = 6,
                [pbr::OriginalName("GET_PARTICIPATIONS")] GetParticipations = 7,
            }

        }
        #endregion

    }

    #endregion

}

#endregion Designer generated code
